Repository service-dida/back_end, pull requests merged in 2023-05, with the labels that each got.

#89 user 이름 변경 관련 리팩토링
  src/main/java/com/service/dida/domain/comment/Comment.java
  src/main/java/com/service/dida/domain/like/Like.java
  src/main/java/com/service/dida/domain/market/Market.java
  src/main/java/com/service/dida/domain/market/MarketService.java
  src/main/java/com/service/dida/domain/member/Role.java
  src/main/java/com/service/dida/domain/member/contorller/GetMemberController.java
  src/main/java/com/service/dida/domain/member/contorller/RegisterMemberController.java
  src/main/java/com/service/dida/domain/member/contorller/UpdateMemberController.java
  src/main/java/com/service/dida/domain/member/dto/MemberRequestDto.java
  src/main/java/com/service/dida/domain/member/dto/MemberResponseDto.java
  src/main/java/com/service/dida/domain/member/dto/SendAuthEmailDto.java
  src/main/java/com/service/dida/domain/member/entity/Member.java
  src/main/java/com/service/dida/domain/member/repository/MemberRepository.java
  src/main/java/com/service/dida/domain/member/service/GetMemberService.java
  src/main/java/com/service/dida/domain/member/service/RegisterMemberService.java
  src/main/java/com/service/dida/domain/member/service/UpdateMemberService.java
  src/main/java/com/service/dida/domain/member/usecase/GetMemberUseCase.java
  src/main/java/com/service/dida/domain/member/usecase/RegisterMemberUseCase.java
  src/main/java/com/service/dida/domain/member/usecase/UpdateMemberUseCase.java
  src/main/java/com/service/dida/domain/nft/Nft.java
  src/main/java/com/service/dida/domain/post/Post.java
  src/main/java/com/service/dida/domain/post/service/PostService.java
  src/main/java/com/service/dida/global/config/security/auth/PrincipalDetails.java
  src/main/java/com/service/dida/global/config/security/auth/PrincipalDetailsService.java
  src/main/java/com/service/dida/global/config/security/jwt/JwtTokenProvider.java
Labels: ⚒refactor

#93 사용자 로그인 어노테이션 및 지갑,계정 api 개발
  src/main/java/com/service/dida/domain/member/Role.java
  src/main/java/com/service/dida/domain/member/contorller/GetMemberController.java
  src/main/java/com/service/dida/domain/member/contorller/RegisterMemberController.java
  src/main/java/com/service/dida/domain/member/contorller/UpdateMemberController.java
  src/main/java/com/service/dida/domain/member/dto/MemberRequestDto.java
  src/main/java/com/service/dida/domain/member/entity/Member.java
  src/main/java/com/service/dida/domain/member/service/GetMemberService.java
  src/main/java/com/service/dida/domain/member/service/UpdateMemberService.java
  src/main/java/com/service/dida/domain/member/usecase/GetMemberUseCase.java
  src/main/java/com/service/dida/domain/member/usecase/UpdateMemberUseCase.java
  src/main/java/com/service/dida/domain/wallet/controller/WalletController.java
  src/main/java/com/service/dida/domain/wallet/dto/WalletResponseDto.java
  src/main/java/com/service/dida/domain/wallet/repository/WalletRepository.java
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
  src/main/java/com/service/dida/domain/wallet/usecase/WalletUseCase.java
  src/main/java/com/service/dida/global/config/security/SecurityConfig.java
  src/main/java/com/service/dida/global/config/security/auth/CurrentMember.java
  src/main/java/com/service/dida/global/config/security/auth/PrincipalDetails.java
  src/main/java/com/service/dida/global/config/security/jwt/JwtTokenProvider.java
Labels: 👩‍💻feature

#95 NFT 생성 및 Transaction 개발
  src/main/java/com/service/dida/domain/member/contorller/UpdateMemberController.java
  src/main/java/com/service/dida/domain/member/dto/MemberRequestDto.java
  src/main/java/com/service/dida/domain/member/service/RegisterMemberService.java
  src/main/java/com/service/dida/domain/nft/Nft.java
  src/main/java/com/service/dida/domain/nft/controller/RegisterNftController.java
  src/main/java/com/service/dida/domain/nft/controller/UpdateNftController.java
  src/main/java/com/service/dida/domain/nft/dto/NftRequestDto.java
  src/main/java/com/service/dida/domain/nft/repository/NftRepository.java
  src/main/java/com/service/dida/domain/nft/service/RegisterNftService.java
  src/main/java/com/service/dida/domain/nft/service/UpdateNftService.java
  src/main/java/com/service/dida/domain/nft/usecase/RegisterNftUseCase.java
  src/main/java/com/service/dida/domain/nft/usecase/UpdateNftUseCase.java
  src/main/java/com/service/dida/domain/transaction/Transaction.java
  src/main/java/com/service/dida/domain/transaction/Type.java
  src/main/java/com/service/dida/domain/transaction/controller/TransactionController.java
  src/main/java/com/service/dida/domain/transaction/dto/TransactionRequestDto.java
  src/main/java/com/service/dida/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/service/dida/domain/transaction/service/TransactionService.java
  src/main/java/com/service/dida/domain/transaction/usecase/TransactionUseCase.java
  src/main/java/com/service/dida/domain/wallet/Wallet.java
  src/main/java/com/service/dida/domain/wallet/repository/WalletRepository.java
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
  src/main/java/com/service/dida/global/common/BaseEntity.java
  src/main/java/com/service/dida/global/common/manage/Manage.java
  src/main/java/com/service/dida/global/common/manage/ManageRepository.java
  src/main/java/com/service/dida/global/common/manage/ManageService.java
  src/main/java/com/service/dida/global/common/manage/ManageUseCase.java
  src/main/java/com/service/dida/global/config/exception/errorCode/NftErrorCode.java
  src/main/java/com/service/dida/global/config/exception/errorCode/WalletErrorCode.java
  src/main/java/com/service/dida/global/util/KasService.java
  src/main/java/com/service/dida/global/util/service/KasService.java
  src/main/java/com/service/dida/global/util/usecase/KasUseCase.java
Labels: 👩‍💻feature

#98 CI_CD 추가
  .github/workflows/github-actions.yml
  .gitignore
  Dockerfile-dev
Labels: ⚙infra

#96 댓글 관련 API 구현
  src/main/java/com/service/dida/domain/comment/Comment.java
  src/main/java/com/service/dida/domain/comment/controller/GetCommentController.java
  src/main/java/com/service/dida/domain/comment/controller/RegisterCommentController.java
  src/main/java/com/service/dida/domain/comment/controller/UpdateCommentController.java
  src/main/java/com/service/dida/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/service/dida/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/service/dida/domain/comment/repository/CommentRepository.java
  src/main/java/com/service/dida/domain/comment/service/GetCommentService.java
  src/main/java/com/service/dida/domain/comment/service/RegisterCommentService.java
  src/main/java/com/service/dida/domain/comment/service/UpdateCommentService.java
  src/main/java/com/service/dida/domain/comment/usecase/GetCommentUseCase.java
  src/main/java/com/service/dida/domain/comment/usecase/RegisterCommentUseCase.java
  src/main/java/com/service/dida/domain/comment/usecase/UpdateCommentUseCase.java
  src/main/java/com/service/dida/domain/post/controller/GetPostController.java
  src/main/java/com/service/dida/domain/post/controller/RegisterPostController.java
  src/main/java/com/service/dida/domain/post/controller/UpdatePostController.java
  src/main/java/com/service/dida/domain/post/dto/PostResponseDto.java
  src/main/java/com/service/dida/domain/post/service/GetPostService.java
  src/main/java/com/service/dida/domain/post/service/RegisterPostService.java
  src/main/java/com/service/dida/domain/post/service/UpdatePostService.java
  src/main/java/com/service/dida/domain/post/usecase/GetPostUseCase.java
  src/main/java/com/service/dida/domain/post/usecase/RegisterPostUseCase.java
  src/main/java/com/service/dida/domain/post/usecase/UpdatePostUseCase.java
  src/main/java/com/service/dida/global/config/exception/errorCode/CommentErrorCode.java
Labels: 👩‍💻feature

#99 Resources 폴더 생성을 위한 임시 파일 추가
  src/main/resources/testfile.xml
Labels: 📄docs
