Repository service-dida/back_end, pull requests merged in 2023-09, with the labels that each got.

#131 페이징 수정 및 로그인 이메일 파싱 수정
  src/main/java/com/service/dida/domain/alarm/controller/AlarmController.java
  src/main/java/com/service/dida/domain/alarm/service/GetAlarmService.java
  src/main/java/com/service/dida/domain/alarm/usecase/GetAlarmUseCase.java
  src/main/java/com/service/dida/global/config/exception/BaseException.java
Labels: ⚒refactor

#132 지갑 생성 과정 수정
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
Labels: ⚒refactor

#133 외부 api 수정
  src/main/java/com/service/dida/domain/nft/service/RegisterNftService.java
  src/main/java/com/service/dida/global/common/CommonController.java
  src/main/java/com/service/dida/global/util/service/KasService.java
Labels: ⚒refactor

#134 NFT 좋아요 누르기 status default 값 수정
  src/main/java/com/service/dida/domain/like/Like.java
  src/main/java/com/service/dida/domain/like/service/RegisterLikeService.java
Labels: :lady_beetle: bug

#135 NFT 내보내는 api url 수정
  src/main/java/com/service/dida/global/util/service/KasService.java
Labels: :lady_beetle: bug

#136 판매 과정 수정
  src/main/java/com/service/dida/domain/market/service/RegisterMarketService.java
  src/main/java/com/service/dida/domain/nft/Nft.java
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
Labels: :lady_beetle: bug

#137 판매 중복 수정
  src/main/java/com/service/dida/domain/market/repository/MarketRepository.java
  src/main/java/com/service/dida/domain/market/service/RegisterMarketService.java
  src/main/java/com/service/dida/global/config/exception/errorCode/MarketErrorCode.java
Labels: :lady_beetle: bug

#138 트랜잭션 정보 수정
  src/main/java/com/service/dida/domain/transaction/dto/TransactionResponseDto.java
  src/main/java/com/service/dida/domain/transaction/service/GetTransactionService.java
Labels: :lady_beetle: bug

#139 거래 트랜잭션 정보 수정
  src/main/java/com/service/dida/domain/transaction/Transaction.java
  src/main/java/com/service/dida/domain/transaction/dto/TransactionResponseDto.java
  src/main/java/com/service/dida/domain/transaction/service/GetTransactionService.java
Labels: :lady_beetle: bug

#141 Nft 관련 Response 수정
  src/main/java/com/service/dida/domain/nft/controller/RegisterNftController.java
  src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
  src/main/java/com/service/dida/domain/nft/service/GetNftService.java
  src/main/java/com/service/dida/domain/nft/service/RegisterNftService.java
  src/main/java/com/service/dida/domain/nft/usecase/RegisterNftUseCase.java
Labels: ⚒refactor

#142 NFT 목록 조회 및 메인화면 Soldout 조회 API 수정
  src/main/java/com/service/dida/domain/market/controller/GetMarketController.java
  src/main/java/com/service/dida/domain/market/dto/MarketResponseDto.java
  src/main/java/com/service/dida/domain/market/service/GetMarketService.java
  src/main/java/com/service/dida/domain/market/usecase/GetMarketUseCase.java
  src/main/java/com/service/dida/domain/member/dto/MemberResponseDto.java
  src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
  src/main/java/com/service/dida/domain/nft/service/GetNftService.java
Labels: 👩‍💻feature, ⚒refactor

#143 프로필 - 보유한 NFT 조회 API 쿼리 수정
  src/main/java/com/service/dida/domain/nft/dto/NftResponseDto.java
  src/main/java/com/service/dida/domain/nft/repository/NftRepository.java
  src/main/java/com/service/dida/domain/nft/service/GetNftService.java
Labels: ⚒refactor

#144 NFT확인 Api 수정 및 미로그인 수정
  src/main/java/com/service/dida/domain/nft/service/GetNftService.java
  src/main/java/com/service/dida/global/config/security/jwt/JwtAuthenticationFilter.java
Labels: ⚒refactor

#145 비밀번호 확인 및 팔로우 목록 API 수정
  src/main/java/com/service/dida/domain/follow/Follow.java
  src/main/java/com/service/dida/domain/follow/dto/FollowResponseDto.java
  src/main/java/com/service/dida/domain/follow/repository/FollowRepository.java
  src/main/java/com/service/dida/domain/follow/service/GetFollowService.java
  src/main/java/com/service/dida/domain/member/entity/Member.java
  src/main/java/com/service/dida/domain/wallet/controller/WalletPasswordController.java
  src/main/java/com/service/dida/domain/wallet/dto/WalletRequestDto.java
  src/main/java/com/service/dida/domain/wallet/service/WalletPasswordService.java
  src/main/java/com/service/dida/domain/wallet/usecase/WalletPasswordUseCase.java
Labels: 👩‍💻feature
