Repository service-dida/back_end, pull requests merged in 2023-10, with the labels that each got.

#146 메인 화면 Recent NFT 리스폰스 개수 수정
  src/main/java/com/service/dida/domain/market/service/GetMarketService.java
Labels: 👩‍💻feature

#147 비밀번호 확인 API 수정
  src/main/java/com/service/dida/domain/wallet/controller/WalletPasswordController.java
  src/main/java/com/service/dida/domain/wallet/dto/WalletResponseDto.java
  src/main/java/com/service/dida/domain/wallet/service/WalletPasswordService.java
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
  src/main/java/com/service/dida/domain/wallet/usecase/WalletPasswordUseCase.java
  src/main/java/com/service/dida/domain/wallet/usecase/WalletUseCase.java
Labels: ⚒refactor

#148 비밀번호 확인 API 수정
  src/main/java/com/service/dida/domain/wallet/dto/WalletRequestDto.java
  src/main/java/com/service/dida/domain/wallet/service/WalletService.java
  src/main/java/com/service/dida/global/common/CommonController.java
Labels: ⚒refactor

#149 비밀번호 변경 기능 로직 변경
  src/main/java/com/service/dida/domain/member/contorller/GetMemberController.java
  src/main/java/com/service/dida/domain/wallet/controller/WalletPasswordController.java
  src/main/java/com/service/dida/domain/wallet/dto/WalletRequestDto.java
  src/main/java/com/service/dida/domain/wallet/service/WalletPasswordService.java
  src/main/java/com/service/dida/domain/wallet/usecase/WalletPasswordUseCase.java
  src/main/java/com/service/dida/global/common/CommonController.java
  src/main/java/com/service/dida/global/util/service/MailService.java
  src/main/java/com/service/dida/global/util/usecase/MailUseCase.java
Labels: ⚒refactor

#150 비밀번호 변경 기능 수정
  src/main/java/com/service/dida/domain/wallet/service/WalletPasswordService.java
Labels: :lady_beetle: bug
